
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package de.unitrier.st.uap;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int AND = 24;
  public static final int LT = 21;
  public static final int ELSE = 6;
  public static final int OR = 25;
  public static final int LTE = 23;
  public static final int THEN = 5;
  public static final int SEMI = 26;
  public static final int IN = 3;
  public static final int WHILE = 8;
  public static final int RBRA = 12;
  public static final int TRUE = 28;
  public static final int IF = 4;
  public static final int LBRA = 11;
  public static final int GT = 20;
  public static final int ID = 30;
  public static final int GTE = 22;
  public static final int SUB = 15;
  public static final int DO = 7;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIV = 17;
  public static final int ADD = 14;
  public static final int FALSE = 29;
  public static final int CONST = 31;
  public static final int error = 1;
  public static final int LET = 2;
  public static final int EQ = 18;
  public static final int ASSIGN = 13;
  public static final int RPAR = 10;
  public static final int NEQ = 19;
  public static final int LPAR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LET",
  "IN",
  "IF",
  "THEN",
  "ELSE",
  "DO",
  "WHILE",
  "LPAR",
  "RPAR",
  "LBRA",
  "RBRA",
  "ASSIGN",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "EQ",
  "NEQ",
  "GT",
  "LT",
  "GTE",
  "LTE",
  "AND",
  "OR",
  "SEMI",
  "COMMA",
  "TRUE",
  "FALSE",
  "ID",
  "CONST"
  };
}

